### ISSUE TITLE
YouTube Player is not attached to the DOM error on OH Index

### ISSUE THREAD

**Issue by boveus** [gsu-library/sirenia#116]
When a user visits an indexed oral history page the 'Play Segment' button does not work.  This is due to the YouTube player not being attached to the DOM:
![image](https://user-images.githubusercontent.com/20469703/42946374-b2d0f114-8b38-11e8-8505-0b87602bdea1.png)

It seems like this is an issue with the order that the JS is loaded compared to the embedded youtube video on the page.  I think the JS is rendering before the video, which causes the JS to not find the embedded link.

**Comment by boveus** [comment]
This is most likely fixed by PR #123.  We can reopen this if this issue pops up again

**Comment by jeremytbright** [comment]
Happened again (until reload) with this OH: http://131.96.19.31/concern/oral_histories/p2676v556?locale=en

**Comment by boveus** [comment]
I think PR #176 may have resolved this.  I'm going to give it a little more time to see if it reoccurs.

**Comment by mosabraouf** [comment]
i had this issue with framework7, and i fixed it .
Maybe you should rest the player by "myPlayer.dispose();" and then recrate it.
