### ISSUE TITLE
Refine workflow surrounding resource types

### ISSUE THREAD

**Issue by boveus** [gsu-library/sirenia#121]
Hey @kmichaelis55 and @jeremytbright,

While I was refactoring I noticed an ambiguity with how new works are getting the 'resource type' assigned.

We are currently setting resource types to default values after a record is created, but we also have a form input to determine the resource type.  In the example below (Using the Photo work) a user can select any of the resource types defined in the CV, but due to how we have configured the default resource type it will be overriden as "still image" regardless of what a user selects.

![image](https://user-images.githubusercontent.com/20469703/43008462-2a3f5a30-8c09-11e8-9e56-2db8b4f25d75.png)

What would be the ideal behavior for this case?  

A) Only override the value when a record is initially created, so you could go back and edit it to another value and that change will be applied.

B) Remove this form element altogether for work types that will *always* have the same resource type.  

C) Make it an optional field rather than a required field and only add the value if there is not one specified in the form.

This won't involve a significant amount of coding to accomplish, so whichever option makes the most sense from a workflow perspective will work.  If there is another option I didn't consider that makes more sense that will work too.

**Comment by kmichaelis** [comment]
I'm leaning toward option A. @jeremytbright  what do you think?

**Comment by jeremytbright** [comment]
Agreed.

J

**Comment by boveus** [comment]
Cool, will do.  Thank y'all.
